name: PR Review - Ruff Lint

on:
  pull_request:
    branches:
      - main

  
jobs:
  ruff-review:
    runs-on: ubuntu-latest
    # Required permissions to post review comments to the PR
    permissions:
      # contents permission to clone the repository
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false # Only scan files changed in the PR
          VALIDATE_PYTHON_RUFF: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
