name: PR Review - Ruff Lint

on:
  pull_request:
    branches:
      - main

jobs:
  ruff_lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github"
